[package]
name = "sagep/Physics-Based-Characters"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Jecs = "ukendio/jecs@0.9.0"
Jabby = "alicesaidhi/jabby@0.3.1"
Replecs = "pepeeltoro41/replecs@0.1.0-alpha9.1"
Planck = "yetanotherclown/planck@0.2.0"
PlanckJabby = "yetanotherclown/planck-jabby@0.2.0"
PlanckRunService = "yetanotherclown/planck-runservice@0.2.0"

[server-dependencies]